name: ci/cd piplelane

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the code
          uses: actions/checkout@v2
          
        - name: setup go
          uses: actions/setup-go@v2
          with:
            go-version: '1.21'

        - name: run test
          run:
            go test -v ./...

    build-and-push-docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: checkout the code
          uses: actions/checkout@v2
          
        - name: create env file
          run:
            echo "${{secrets.ENV }}" >> .env
          
        - name: build docker
          run:
            docker build -t barmono/clean_arsitectur_test:terbaru .
        - name : docker hub login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
            
        - name: push image
          run:
            docker push barmono/clean_architectur_test:terbaru

        